	const_def

	;PlayerGender
	const ENGINE_PLAYER_IS_FEMALE
	
	;wIsDST
	const ENGINE_DST
	
	;BikeFlags
	const ENGINE_STRENGTH_ACTIVE
	const ENGINE_ALWAYS_ON_BIKE
	const ENGINE_DOWNHILL
	
	;StatusFlags
	const ENGINE_POKEDEX
	const ENGINE_HARDMODE
	const ENGINE_POKERUS
	const ENGINE_EXP_ALL
	const ENGINE_CREDITS_SKIP
	const ENGINE_BUG_CONTEST_ON
	
	;StatusFlags2
	const ENGINE_BUG_CONTEST_TIMER
	const ENGINE_FAST_TMHM
	
	;Badges
	const ENGINE_CORAL_EYE_BADGE
	const ENGINE_SEA_RUBY_BADGE
	const ENGINE_SPIKE_SHELL_BADGE
	const ENGINE_JADE_STAR_BADGE
	
	;Flypoints
	;VisitedSpawns
	const ENGINE_FLYPOINT_KRISS_HOUSE
	const ENGINE_FLYPOINT_VALENCIA
	const ENGINE_FLYPOINT_TANGELO
	const ENGINE_FLYPOINT_MIKAN
	const ENGINE_FLYPOINT_ROUTE_52
	const ENGINE_FLYPOINT_MANDARIN_NORTH
	const ENGINE_FLYPOINT_SUNBURST
	const ENGINE_FLYPOINT_ROUTE_56	; route 56 west Pokécenter
	
	;VisitedSpawns + 1
	const ENGINE_FLYPOINT_KINNOW
	const ENGINE_FLYPOINT_NAVEL
	const ENGINE_FLYPOINT_MORO
	const ENGINE_FLYPOINT_MURCOTT
	const ENGINE_FLYPOINT_TROVITOPOLIS
	const ENGINE_FLYPOINT_TROVITA
	const ENGINE_FLYPOINT_ASCORBIA
	const ENGINE_FLYPOINT_KUMQUAT
	
	;VisitedSpawns + 2
	const ENGINE_FLYPOINT_PUMMELO
	const ENGINE_FLYPOINT_HAMLIN
	const ENGINE_FLYPOINT_SHAMOUTI
	const ENGINE_FLYPOINT_VERMILION
	
	;wDaycareMan
	const ENGINE_DAYCARE_MAN_HAS_EGG
	const ENGINE_DAYCARE_MAN_HAS_MON
	
	;wDaycareLady
	const ENGINE_DAYCARE_LADY_HAS_MON
	
	;DailyFlags
	const ENGINE_DAILY_BUG_CONTEST
	const ENGINE_BARGAINED_TODAY
	const ENGINE_MASSAGED_TODAY
	
	;WeeklyFlags
	const ENGINE_TEA_IN_BLUES_HOUSE
	const ENGINE_GOT_HAIRCUT
	
	;SwarmFlags
	const ENGINE_GOLDENROD_DEPT_STORE_SALE_IS_ON
	
	;wLuckyNumberShowFlag
	const ENGINE_LUCKY_NUMBER_SHOW
	
	;wPlayerSpriteSetupFlags
	const ENGINE_KRIS_IN_CABLE_CLUB
	
	;SwarmFlags
	const ENGINE_YANMA_SWARM

NUM_ENGINE_FLAGS EQU const_value
